### ISSUE TITLE
Implement Shadowing when moving mouse over the matrix

### ISSUE THREAD

**Issue by mmahmoudian** [UbuntuBudgie/window-shuffler#10]
I'm a long time user of gTile and now that I have migrated out of Gnome, I feel that some features are very necessary here. One of those features is the shadowing. Meaning when user move their mouse over the tiles in the matrix, they see a shadow on the actual monitor on how the window will look like.

I think this video can help conveying my message:
https://www.youtube.com/watch?v=uqgsVerrWy0

**Comment by fossfreedom** [comment]
Interesting idea. Currently exploring a rewrite using vala on our experimental repo. Could be a nice issue for talented people to explore with us

https://github.com/ubuntubudgie/experimental

**Comment by fossfreedom** [comment]
ok - to kick start.

For vala we'll need to use this vapi https://github.com/GNOME/vala/blob/master/vapi/clutter-gtk-1.0.vapi

Straightforward clutter + GTK integration are here (in C) https://github.com/GNOME/clutter-gtk/tree/master/examples - but should be easily enough to understand when translating to vala

----

The equiv for python - python-clutter gtk is available if you install the package gir1.2-gtkclutter-1.0

https://gist.github.com/sahib/5518543 for an interesting example

https://lazka.github.io/pgi-docs/#GtkClutter-1.0

**Comment by fossfreedom** [comment]
Resolved in the new window-shuffler available on the repo budgie-extras
