### ISSUE TITLE
Add more boxes to the grid? (Seems to be a hard limit on 6x6)

### ISSUE THREAD

**Issue by tdoerrich** [UbuntuBudgie/window-shuffler#11]
Hello! So I'm using the Budgie Window Shuffler on a Ultrawide monitor, and for me the 6x6 grid is a bit too small. Is there anyway to make this number a bit higher? (Eg. 10x10 or something similar). I have tried to add more but it seems to be a limit on the 6x6 number. This makes me not really be able to divide the screen in a good way as I have several apps open.

**Comment by Jacob-Vlijm** [comment]
Shuffler is about to see a second version (vala based). This one will be much more responsive, and also scaling savvy, which the old one wasn't. On a 4k monitor (scaling 200%) I must say windows easily meet their minimum size, especially e.g. Tilix etc. I will however include a gsettings max to 6 x 6, which you can set to a max of 10x10 in dconf (setting available in a settings window).
The new shuffler will be the default in 20.04.

**Comment by fossfreedom** [comment]
@TobiasDev will you be willing to help us test the new shuffler?

If yes,  let us know what version of UB you are using.

We will ping you when the testing version is ready.

**Comment by tdoerrich** [comment]
I wouldn't mind testing, though I'm using this on Solus and not Ubuntu Budgie, if that makes a difference?

**Comment by fossfreedom** [comment]
Resolved in the new window-shuffler available on the repo budgie-extras
