### ISSUE TITLE
Not working as intended on High resolution display.

### ISSUE THREAD

**Issue by Alex0s** [UbuntuBudgie/window-shuffler#2]
Hello,
Im using Ubuntu Budgie on a Matebook Pro laptop which has a 3000x2000 native resolution but window-shuffler is probably stuck at 1920x1080 or something, because half the screen isnt covered. 

Here is a [screenshot](https://imgur.com/a/YdpX7ws) of me trying to put chrome on the most right Tile. It barely go half way horizontally and same for Y axis. Newbie on git and bug report, sorry if not properly reported, love Ubuntu budgie otherwise.

**Comment by Gintoki1ku** [comment]
@Alex0s It's the same with me. It will be normal if I close Hidpi.

**Comment by Alex0s** [comment]
Yep, the issue is gone when reverting back to 100% scaling, when the bug occured at the native 200% scaling. So it's definitly an issue between shufler and the scaling on Hidpi.

**Comment by fossfreedom** [comment]
Resolved in the new window-shuffler available on the repo budgie-extras
