### ISSUE TITLE
AttributeError: 'X11Display' object has no attribute 'get_monitor_at_point'

### ISSUE THREAD

**Issue by hugobuddel** [UbuntuBudgie/window-shuffler#3]
The GUI starts nicely, but this error shows in the terminal as soon as I interact with the window (e.g. try to assign a window to a grid position:
````
Traceback (most recent call last):
  File "[..]/window-shuffler/window_shuffler", line 469, in move_
window
    win_geodata = geo.get_windows_oncurrent(self.screendata)
  File "[..]/window-shuffler/shuffler_geo.py", line 114, in get_$
indows_oncurrent
    currmonitor = get_currmonitor_atpos(mp[0], mp[1])
  File "[..]/window-shuffler/shuffler_geo.py", line 44, in get_c$
rrmonitor_atpos
    return display.get_monitor_at_point(x, y)
AttributeError: 'X11Display' object has no attribute 'get_monitor_at_point'
````
The window is not moved.

**Comment by hugobuddel** [comment]
More info: using Mate on Ubuntu 16.04.5 LTS, window-shuffler was suggested in this post: https://askubuntu.com/a/1044881/583166

Perhaps one of my libraries is too old? A quick google search didn't give much useful information.

**Comment by Jacob-Vlijm** [comment]
I can't test it, since I don't have a 16.04, but yeah, I am pretty sure it won't run on 16.04, given the message. Sorry I don't have a fix for that. It was developed on 18.04. There were quite a few changes in the past few years.

**Comment by hugobuddel** [comment]
Thanks for your replay @Jacob-Vlijm. Could you perhaps give me a pointer about which library actually is outdated? Maybe it is possible to upgrade it. python-gi-cairo?

**Comment by fossfreedom** [comment]
You will need to look at the gtk api itself. The function used is gtk3.22 and later.  You will need to find an equivalent gtk 3.18 method. 

It will not be a simple "upgrade this package" approach. It will need compatible code changes

**Comment by hugobuddel** [comment]
Ah ok, upgrading gtk might be messy. Seems doable though: https://askubuntu.com/questions/830832/update-gnome-on-ubuntu-16-04

I'll try later today.

**Comment by hugobuddel** [comment]
Hmm adding `ppa:gnome3-team/gnome3-staging` gives this warning:
> This PPA is no longer updated for releases older than Ubuntu 18.04 LTS. If you are using an older release, please ppa-purge this PPA and consider upgrading to a newer Ubuntu release.

Perhaps it is time to upgrade my OS, but that will wait to some other moment. I'll close this issue
