### ISSUE TITLE
Focus keeps getting stolen

### ISSUE THREAD

**Issue by hugobuddel** [UbuntuBudgie/window-shuffler#4]
The GUI seems to keep stealing focus. That is, when I start `matrix_wrapper` (but not interacting with it), then I can't really use any other program, because about every second the focus is moved from the active window (to the window shuffler GUI I think). This message pops up on the terminal also about every second, might be related:
> Defaulting to search window name, class, and classname

Using window shuffler on MATE on Ubuntu 16.04.5 LTS.

**Comment by Jacob-Vlijm** [comment]
Using shuffler with gui, it is _meant_ to steal focus, until you click on a segment to move the targeted (last-clicked or selected- ) window., and shuffler is dismissed.

**Comment by hugobuddel** [comment]
ah ok, and that does not work on my setup due to #3
