### ISSUE TITLE
difficulty installing ... Non-ASCII character '\xc2

### ISSUE THREAD

**Issue by P4prik4** [UbuntuBudgie/window-shuffler#5]
linux noob< more a help request than issue. 
following this guide to make shortcut: 
"Run the wrapper matrix_wrapper from either a shortcut or a hotcorner. Running the wrapper again toggles the grid." 

EDIT figured it out

added this line
# -*- coding: utf-8 -*-
at top of 
matrix_wrapper
and shuffler_tools.py

initial goof:

cd "/home/user/wind switch/window-shuffler-master"
sudo chmod +x matrix_wrapper
#! /usr/bin/env python

then typed:
python ./matrix_wrapper

now i got this error: 
user@user-desktop:~/wind switch/window-shuffler-master$ python matrix_wrapper
  File "matrix_wrapper", line 11
SyntaxError: Non-ASCII character '\xc2' in file matrix_wrapper on line 12, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

also made dumb error of typing .py when wasn't called for. 
python ./matrix_wrapper.py  or python matrix_wrapper.py 
to which i got: 
python: can't open file './matrix_wrapper.py': [Errno 2] No such file or directory

**Comment by P4prik4** [comment]
so i got it running the first time
now i try to repeat
python ./matrix_wrapper
Traceback (most recent call last):
  File "./matrix_wrapper", line 7, in <module>
    from shuffler_tools import get_window, app_path
  File "/home/paprika/wind switch/window-shuffler-master/shuffler_tools.py", line 35, in <module>
    except FileExistsError:
NameError: name 'FileExistsError' is not defined


hot corner isnt working either at all ... sheesh

**Comment by fossfreedom** [comment]
what operating system are you using?

This is a python3 application - so you need to run `python3 ./matrix_wrapper`

Running `python ./matrix_wrapper` will try to run stuff with python2

**Comment by P4prik4** [comment]
python 3...  works thanks
i think i might of installed older python library futzing around

using:Ubuntu 18.04 bionic w/ latest budgie (minimal install) 
well i got hotcorner working reinstalled it, used budgie applets snap from software store
also did apt-get update 
and upgrade

what action do i type in hotcorner? 


winging it here but do i make a shortcut the .desktop way
something like

[Desktop Entry]
Encoding=UTF-8
Version=1.0                                     
Name[en_US]=windowshuffler                              
GenericName=window switcher                   
Exec=cd "/home/paprika/wind switch/window-shuffler-master" && #! /usr/bin/env python && prython ./matrix_wrapper

idk if && is right

Terminal=true                                 
Icon[en_US]=  
Type=Application                                
Categories=Application;UI;Settings;        
Comment[en_US]=switcher shuffler

**Comment by fossfreedom** [comment]
Just put the full path to matrix wrapper where-ever you installed it

e.g. `python3 /usr/share/budgie-desktop/windowshuffler/matrix_wrapper`

If you `chmod +x matrix_wrapper` you don't need the `python3` prefix.

**Comment by P4prik4** [comment]
perfecto you rock and nice username to boot. 
thanks for bearing with me
