### ISSUE TITLE
pressing squares & nothing happens

### ISSUE THREAD

**Issue by P4prik4** [UbuntuBudgie/window-shuffler#6]
me again, 
had it working yesterday but only briefly
terminal says IndexError: list index out of range

i tried just deleting the install folder and start over from a fresh extract
but still same issue, 

could it be there's like residual from last install?

**Comment by Jacob-Vlijm** [comment]
"terminal says indexerror" - on what exactly, what command, and what is the full error message?

**Comment by P4prik4** [comment]
commands I've tried
```
python3 /usr/share/budgie-desktop/windowshuffler/matrix_wrapper

```

`python3 ./usr/share/budgie-desktop/windowshuffler/matrix_wrapper`

`python3 /usr/share/budgie-desktop/windowshuffler/window_shuffler`



```
#! /usr/bin/env python
sudo chmod +x matrix_wrapper
python3 ./matrix_wrapper
```

to any of the above this is the result i get: when i press a square: 

```
Defaulting to search window name, class, and classname
Defaulting to search window name, class, and classname
Traceback (most recent call last):
  File "/usr/share/budgie-desktop/windowshuffler/window_shuffler", line 469, in move_window
    win_geodata = geo.get_windows_oncurrent(self.screendata)
  File "/usr/share/budgie-desktop/windowshuffler/shuffler_geo.py", line 136, in get_windows_oncurrent
    dockgeo = [get_strut(str(d.get_xid())) for d in otherdocks]
  File "/usr/share/budgie-desktop/windowshuffler/shuffler_geo.py", line 136, in <listcomp>
    dockgeo = [get_strut(str(d.get_xid())) for d in otherdocks]
  File "/usr/share/budgie-desktop/windowshuffler/shuffler_geo.py", line 73, in get_strut
    ][0].split("=")[1].strip().split(",")
IndexError: list index out of range
Defaulting to search window name, class, and classname
Defaulting to search window name, class, and classname
Defaulting to search window name, class, and classname
```

**Comment by Jacob-Vlijm** [comment]
What is your Ubuntu version?

**Comment by P4prik4** [comment]
don't bother, likely on my end.  using latest but i'll be redoing a fresh install anyways, played around, i think too much.  no worries.
