### ISSUE TITLE
How to disable it?

### ISSUE THREAD

**Issue by Plandercozeron** [UbuntuBudgie/window-shuffler#7]
kUbuntu 18.10. Got this error
```
@:~/git_projects/WindowTiling/window-shuffler$ ./matrix_wrapper
Traceback (most recent call last):
  File "./matrix_wrapper", line 6, in <module>
    from shuffler_tools import get_window, app_path
  File "/home/andrew/git_projects/WindowTiling/window-shuffler/shuffler_tools.py", line 5, in <module>
    gi.require_version("Wnck", "3.0")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 127, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Wnck not available
```
But it seems that wrapper started anyway because windows have gray borders. Can't see anything via htop/ps aux. How do i disable it?

**Comment by Jacob-Vlijm** [comment]
Are you running windowshuffler on Kubuntu? Anyway, Wnck seems not installed: `apt-get install python3-gi gir1.2-wnck-3.0` 
What exactly would you like to disable?

**Comment by Plandercozeron** [comment]
> What exactly would you like to disable?

Non-active windows have grey borders. Can't find process which've been triggered. Not a big deal, actually. Just asking. Reboot should help
> Wnck seems not installed

Oops, thanks.
Will give another another try

**Comment by Plandercozeron** [comment]
Yep, it works now. Very useful. Going to use it with scrcpy =)
